services:
  dynamodb:
    image: zestyco/dynamodb-challenge:amd
    ports:
      - "8000:8000"
  go-web:
    image: tomerleib/goapp:latest
    ports:
      - "8080:8080"
    volumes:
      - ~/.aws:/root/.aws    
    depends_on:
      - dynamodb
    environment:
      - DYNDB=http://dynamodb:8000      